In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel('StarWars.xlsx')

In [3]:
df

respondentID seen  fan gender age_group             income  \
0       3292879998   да   да      М     18-29                NaN   
1       3292879538  нет  NaN      М     18-29         0 - 24.999   
2       3292765271   да  нет      М     18-29         0 - 24.999   
3       3292763116   да   да      М     18-29  100.000 - 149.999   
4       3292731220   да   да      М     18-29  100.000 - 149.999   
...            ...  ...  ...    ...       ...                ...   
1181    3288388730   да   да      Ж     18-29         0 - 24.999   
1182    3288378779   да   да      Ж     30-44    50.000 - 99.999   
1183    3288375286  нет  NaN      Ж     30-44    50.000 - 99.999   
1184    3288373068   да   да      Ж     45-60  100.000 - 149.999   
1185    3288372923   да  нет      Ж      > 60    50.000 - 99.999   

                               loc                      yoda  \
0               Южно-Атлантический            очень нравится   
1         Юго-Западный центральный                       NaN   
2      Северо-Западный центральный  не знаю такого персонажа   
3      Северо-Западный центральный            очень нравится   
4      Северо-Западный центральный                  нравится   
...                            ...                       ...   
1181  Северо-Восточный центральный            очень нравится   
1182                        Горный            очень нравится   
1183          Средне-Атлантический                       NaN   
1184  Северо-Восточный центральный            очень нравится   
1185                 Тихоокеанский         очень не нравится   

     princess_leia_organa  
0          очень нравится  
1                     NaN  
2                нравится  
3          очень нравится  
4                нравится  
...                   ...  
1181             нравится  
1182       очень нравится  
1183                  NaN  
1184       очень нравится  
1185       очень нравится  

[1186 rows x 9 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1186 entries, 0 to 1185
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   respondentID          1186 non-null   int64 
 1   seen                  1186 non-null   object
 2   fan                   836 non-null    object
 3   gender                1046 non-null   object
 4   age_group             1046 non-null   object
 5   income                858 non-null    object
 6   loc                   1043 non-null   object
 7   yoda                  826 non-null    object
 8   princess_leia_organa  831 non-null    object
dtypes: int64(1), object(8)
memory usage: 83.5+ KB


1. К какой шкале относится переменная age_group? Выберите один верный ответ.

In [6]:
df.age_group.unique()

array(['18-29', nan, '30-44', '> 60', '45-60'], dtype=object)

2. Верно ли следующее утверждение: все женщины старше 60 лет, входящие в категорию с наивысшим доходом и являющиеся фанатами серии фильмов, проживают в одном регионе. 

In [9]:
df.gender.unique()

array(['М', nan, 'Ж'], dtype=object)

In [10]:
df.income.unique()

array([nan, '0 - 24.999', '100.000 - 149.999', '25.000 - 49.999',
       '50.000 - 99.999', '150.000+'], dtype=object)

In [15]:
df.fan.unique()

array(['да', nan, 'нет'], dtype=object)

In [22]:
conditions = (df['age_group'] == '> 60') & \
             (df['gender'] == 'Ж') & \
             (df['income'] == '150.000+') & \
             (df['fan'] == 'да')

In [24]:
df[conditions]

respondentID seen fan gender age_group    income  \
162    3291141478   да  да      Ж      > 60  150.000+   
522    3290342102   да  да      Ж      > 60  150.000+   
671    3289963393   да  да      Ж      > 60  150.000+   

                             loc            yoda princess_leia_organa  
162                Тихоокеанский  очень нравится       очень нравится  
522  Северо-Западный центральный  очень нравится       очень нравится  
671                       Горный  очень нравится       очень нравится

In [23]:
df[conditions]['loc'].unique()

array(['Тихоокеанский', 'Северо-Западный центральный', 'Горный'],
      dtype=object)

3. Какой регион проживания чаще всего встречается в данных? Выберите один верный ответ.

In [80]:
# df.groupby('loc')['loc'].count().sort_values()
df['loc'].value_counts()

Северо-Восточный центральный    181
Тихоокеанский                   175
Южно-Атлантический              170
Средне-Атлантический            122
Юго-Западный центральный        110
Северо-Западный центральный      93
Горный                           79
Новая Англия                     75
Юго-Восточный центральный        38
Name: loc, dtype: int64

In [81]:
df['loc'].value_counts(dropna=False)

Северо-Восточный центральный    181
Тихоокеанский                   175
Южно-Атлантический              170
NaN                             143
Средне-Атлантический            122
Юго-Западный центральный        110
Северо-Западный центральный      93
Горный                           79
Новая Англия                     75
Юго-Восточный центральный        38
Name: loc, dtype: int64

4. Сколько респондентов не назвали свой доход? Выберите один верный ответ.

In [35]:
df['income'].isna().sum()

328

5. Скольким респондентам одновременно очень нравятся Йода и принцесса Лея Органа? Выберите один верный ответ.

In [36]:
df['yoda'].unique()

array(['очень нравится', nan, 'не знаю такого персонажа', 'нравится',
       'очень не нравится', 'отношусь нейтрально', 'не нравится'],
      dtype=object)

In [37]:
yoda_leia_condition = (df['yoda'] == 'очень нравится') & \
                      (df['princess_leia_organa'] == 'очень нравится')

In [40]:
df[yoda_leia_condition].shape[0]

462

6. Сколько респондентов не видели ни одного фильма серии, но считают себя ее фанатами? Введите ответ в виде целого числа.

In [54]:
df.seen.unique()

array(['да', 'нет'], dtype=object)

In [45]:
fans_without_watching = (df['seen'] == 'нет') & \
                        (df['fan'] == 'да')

In [47]:
df[fans_without_watching].shape[0]

0

In [50]:
df[df['seen'] == 'нет']['fan'].unique()

array([nan], dtype=object)

7. Сколько респондентов не ответили ни на один вопрос? Введите ответ в виде целого числа.

In [52]:
no_answers = (df['seen'].isna())

In [53]:
df[no_answers]

Empty DataFrame
Columns: [respondentID, seen, fan, gender, age_group, income, loc, yoda, princess_leia_organa]
Index: []

7. Посмотрите на мужчин, проживающих в горном районе. В ответ запишите ID респондента, входящего в категорию с наивысшим доходом при заданных условиях.

In [56]:
df['loc'].unique()

array(['Южно-Атлантический', 'Юго-Западный центральный',
       'Северо-Западный центральный', 'Средне-Атлантический',
       'Северо-Восточный центральный', 'Тихоокеанский', nan, 'Горный',
       'Новая Англия', 'Юго-Восточный центральный'], dtype=object)

In [61]:
rich_men_from_mountains = (df['loc'] == 'Горный') & \
                          (df['gender'] == 'М') & \
                          (df['income'] == '150.000+')

In [63]:
df[rich_men_from_mountains]

respondentID seen  fan gender age_group    income     loc      yoda  \
169    3291077381   да  нет      М     45-60  150.000+  Горный  нравится   

    princess_leia_organa  
169  отношусь нейтрально

8. Укажите, верно ли следующее утверждение: фанатов серии фильмов в возрастной категории 45-60 меньше, чем не-фанатов в возрастной категории 18-29. 

In [65]:
fans_45_60_condition = (df['fan'] == 'да') & \
                       (df['age_group'] == '45-60')

In [67]:
df[fans_45_60_condition].shape[0]

154

In [68]:
not_fans_18_29_condition = (df['fan'] == 'нет') & \
                       (df['age_group'] == '18-29')

In [70]:
df[not_fans_18_29_condition].shape[0]

56

In [71]:
df[fans_45_60_condition].shape[0] < df[not_fans_18_29_condition].shape[0]

False

9. Сколько процентов (от общего числа респондентов) являются фанатами серии фильмов, проживают в Новой Англии и имеют доход 0 - 24.999 долларов? В ответ запишите число (процент от 0 до 100), округлите до целого.

In [72]:
df['loc'].unique()

array(['Южно-Атлантический', 'Юго-Западный центральный',
       'Северо-Западный центральный', 'Средне-Атлантический',
       'Северо-Восточный центральный', 'Тихоокеанский', nan, 'Горный',
       'Новая Англия', 'Юго-Восточный центральный'], dtype=object)

In [73]:
df['income'].unique()

array([nan, '0 - 24.999', '100.000 - 149.999', '25.000 - 49.999',
       '50.000 - 99.999', '150.000+'], dtype=object)

In [74]:
poor_fans_from_ne = (df['fan'] == 'да') & \
                    (df['loc'] == 'Новая Англия') & \
                    (df['income'] == '0 - 24.999')

In [78]:
df[poor_fans_from_ne].shape[0]/df.shape[0]*100

0.7588532883642496